name: 'Setup Python Environment'
description: 'Setup Python, cache venv, and install dependencies for Weather Backend'

inputs:
  gcp-sa-key:
    description: 'GCP Service Account Key (base64 encoded)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ensure venv is activated
      shell: bash
      run: |
        # 確保虛擬環境在後續步驟中可用
        echo "VIRTUAL_ENV=${{ github.workspace }}/.venv" >> $GITHUB_ENV
        echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

    - name: Decode GCP Service Account Key
      shell: bash
      run: |
        echo "${{ inputs.gcp-sa-key }}" | base64 --decode > "${{ runner.temp }}/gcp-key.json"
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV
