name: Scheduled Weather Data Updates

on:
  # 允許手動從 GitHub Actions 頁面觸發此工作流程，方便測試
  workflow_dispatch:
    inputs:
      task_name:
        description: '手動執行單一任務的名稱 (例如 update_radar)，留空則執行所有任務'
        required: false
        default: ''

  schedule:
    # 使用 CRON 語法定義排程
    # 註解：CRON 時間為 UTC，比台灣時間慢 8 小時
    
    # 每 10 分鐘執行一次 (用於 radar, current_weather)
    - cron: '*/10 * * * *'
    
    # 每小時的第 20 分鐘執行一次 (用於 uv, air_quality)
    - cron: '0 * * * *'
    
    # 每 3 小時執行一次 (用於 3-hour)
    - cron: '0 */3 * * *'
    
    # 每天 UTC 時間 06:00 和 18:00 執行一次 (用於 weekly)
    - cron: '0 6,18 * * *'
    
    # 每天 UTC 時間 16:00 (台灣時間午夜 00:00) 執行一次 (用於 sunrise_sunset)
    - cron: '0 16 * * *'

  # 允許透過 API 外部觸發
  repository_dispatch:
    types: [run-single-task]

jobs:
  run-tasks:
    # 在最新的 Ubuntu 虛擬環境中執行
    runs-on: ubuntu-latest
    
    steps:
      # 步驟 1: 從您的儲存庫下載程式碼到虛擬環境
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 步驟 2: 設定您指定的 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 您可以根據需求更改此版本

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      # 步驟 3: 安裝專案所需的 Python 套件
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 步驟 4: 將 GCP 服務帳號金鑰從 Secret 還原成檔案 (安全作法)
      - name: Decode GCP Service Account Key
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > "${{ runner.temp }}/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV

      # 步驟 5: 根據排程時間執行對應的 Python 腳本任務
      - name: Run Scheduled Tasks
        # 將所有 GitHub Secrets 和 Variables 設為環境變數
        env:
          # --- 從 Secrets 讀取 (敏感資料) ---
          CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
          NCDR_API_KEY: ${{ secrets.NCDR_API_KEY }}
          MONEV_API_KEY: ${{ secrets.MONEV_API_KEY }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          # --- 從 Variables 讀取 (非敏感設定) ---
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
          R2_ENDPOINT_URL: ${{ vars.R2_ENDPOINT_URL }}
          # 如果您也將這些設為 Variables，請取消註解並使用
          # FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          # USE_EMULATOR: ${{ vars.USE_EMULATOR }}
        run: |
          source .venv/bin/activate
          # 檢查是否為手動或外部 API 觸發，且有指定單一任務
          if [[ ( "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.task_name }}" != "" ) || ( "${{ github.event_name }}" == "repository_dispatch" ) ]]; then
            # 取得要執行的任務名稱
            TASK_TO_RUN=""
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              TASK_TO_RUN="${{ github.event.inputs.task_name }}"
            else # repository_dispatch
              TASK_TO_RUN="${{ github.event.client_payload.task }}"
            fi
            
            echo "Running single task: $TASK_TO_RUN"
            python functions/main.py "$TASK_TO_RUN"
            exit 0 # 執行完畢後直接結束
          fi

          # 如果是手動觸發但未指定任務，則執行所有任務
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.task_name }}" == "" ]]; then
            echo "Manual trigger: Running all tasks for testing..."
            python functions/main.py update_current_weather || true
            python functions/main.py update_radar || true
            python functions/main.py update_three_hour_forecast || true
            python functions/main.py update_weekly_forecast || true
            python functions/main.py update_uv_index || true
            python functions/main.py update_air_quality || true
            python functions/main.py update_sunrise_sunset || true
            exit 0
          fi

          # --- 以下為排程觸發的任務 ---

          # 每 10 分鐘執行的任務
          if [[ "${{ github.event.schedule }}" == "*/10 * * * *" ]]; then
            echo "Running 10-minute tasks..."
            python functions/main.py update_radar || true
          fi
          
          # 每小時執行的任務
          if [[ "${{ github.event.schedule }}" == "0 * * * *" ]]; then
            echo "Running hourly tasks..."
            python functions/main.py update_current_weather || true
            python functions/main.py update_uv_index || true
            python functions/main.py update_air_quality || true
          fi

          # 每 3 小時執行的任務
          if [[ "${{ github.event.schedule }}" == "0 */3 * * *" ]]; then
            echo "Running 3-hourly tasks..."
            python functions/main.py update_three_hour_forecast || true
          fi

          # 每日兩次的任務 (6:00, 18:00 UTC)
          if [[ "${{ github.event.schedule }}" == "0 6,18 * * *" ]]; then
            echo "Running twice-daily tasks..."
            python functions/main.py update_weekly_forecast || true
          fi

          # 每日執行的任務
          if [[ "${{ github.event.schedule }}" == "0 16 * * *" ]]; then
            echo "Running daily tasks..."
            python functions/main.py update_sunrise_sunset || true
          fi
