# This workflow runs the weekly forecast update task twice a day.
# It can also be triggered manually from the Actions tab.

name: Task - Weekly Forecast (Twice Daily)

on:
  schedule:
    # Runs at 06:00 and 18:00 UTC
    - cron: '0 6,18 * * *'
  
  workflow_dispatch:

jobs:
  run-twice-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          gcp-sa-key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Run Weekly Forecast Task
        env:
          CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
          NCDR_API_KEY: ${{ secrets.NCDR_API_KEY }}
          MONEV_API_KEY: ${{ secrets.MONEV_API_KEY }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
          R2_ENDPOINT_URL: ${{ vars.R2_ENDPOINT_URL }}
        run: |
          python functions/main.py update_weekly_forecast
