# This workflow runs the radar update task every 10 minutes.
# It can also be triggered manually from the Actions tab.

name: Task - Radar (10-Minutely)

on:
  #Use workflow_dispatch to allow api triggering
  
  workflow_dispatch:

jobs:
  run-radar-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          gcp-sa-key: ${{ secrets.GCP_SA_KEY_BASE64 }}
          cwa-api-key: ${{ secrets.CWA_API_KEY }}
          ncdr-api-key: ${{ secrets.NCDR_API_KEY }}
          monev-api-key: ${{ secrets.MONEV_API_KEY }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          r2-bucket-name: ${{ vars.R2_BUCKET_NAME }}
          r2-endpoint-url: ${{ vars.R2_ENDPOINT_URL }}

      - name: Run Radar Update Task
        run: |
          python functions/main.py update_radar
