# This workflow runs hourly update tasks concurrently.
# It can also be triggered manually from the Actions tab, which will run all jobs in parallel.

name: Task - Hourly Updates (Concurrent)

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  
  workflow_dispatch:

jobs:
  # Job 1: Update Current Weather
  update-current-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          gcp-sa-key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Run Current Weather Task
        env:
          CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
          NCDR_API_KEY: ${{ secrets.NCDR_API_KEY }}
          MONEV_API_KEY: ${{ secrets.MONEV_API_KEY }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
          R2_ENDPOINT_URL: ${{ vars.R2_ENDPOINT_URL }}
        run: |
          python functions/main.py update_current_weather

  # Job 2: Update UV Index
  update-uv-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          gcp-sa-key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Run UV Index Task
        env:
          CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
          NCDR_API_KEY: ${{ secrets.NCDR_API_KEY }}
          MONEV_API_KEY: ${{ secrets.MONEV_API_KEY }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
          R2_ENDPOINT_URL: ${{ vars.R2_ENDPOINT_URL }}
        run: |
          python functions/main.py update_uv_index

  # Job 3: Update Air Quality
  update-air-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          gcp-sa-key: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Run Air Quality Task
        env:
          CWA_API_KEY: ${{ secrets.CWA_API_KEY }}
          NCDR_API_KEY: ${{ secrets.NCDR_API_KEY }}
          MONEV_API_KEY: ${{ secrets.MONEV_API_KEY }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
          R2_ENDPOINT_URL: ${{ vars.R2_ENDPOINT_URL }}
        run: |
          python functions/main.py update_air_quality
